// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"github.com/google/uuid"
)

type Tenant struct {
	ID uuid.UUID `json:"id"`
}

type Usuario struct {
	ID       uuid.UUID     `json:"id"`
	Email    string        `json:"email"`
	Senha    string        `json:"senha"`
	IDTenant uuid.NullUUID `json:"id_tenant"`
}
