// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context) (uuid.UUID, error)
	CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error)
	SelectUsuarioPorEmail(ctx context.Context, email string) (Usuario, error)
}

var _ Querier = (*Queries)(nil)
