// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
insert into tenant default values returning id
`

func (q *Queries) CreateTenant(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTenant)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
